version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: nas.local
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.29.200 # ipv4_Address & ServerIP will be the pihole admin page
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 5000:5000
      - 5001:5001
    environment:
      ServerIP: 192.168.29.200 # match ipv4_address
      VIRTUAL_HOST: pihole.nas.local # hostname + domainname
      WEBPASSWORD: ""
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.29.0/24
          gateway: 192.168.29.1
          ip_range: 192.168.29.192/28
